# Generated by Django 2.0 on 2018-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an admin.', verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a student.', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a teacher.', verbose_name='teacher'),
        ),
    ]
