# Generated by Django 2.0 on 2018-01-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180115_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselist',
            name='semester',
            field=models.CharField(choices=[('A', '秋'), ('S', '春')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
