# Generated by Django 2.0 on 2018-01-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_courselist_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_zh', models.BooleanField(default='True', verbose_name='is_zh')),
                ('company_zh', models.CharField(max_length=80, verbose_name='company_zh')),
                ('company_en', models.CharField(blank=True, max_length=150, verbose_name='company_zh')),
                ('position', models.CharField(blank=True, default='intern', max_length=10, verbose_name='position')),
                ('st_time', models.DateField()),
                ('ed_time', models.DateField()),
                ('contribution', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
